[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "git submodule init && git submodule update && hugo -b gabe.kitchen --gc --minify"

[context.deploy-preview]
  command = "git submodule init && git submodule update && hugo -b gabe.kitchen --gc --minify"

[context.branch-deploy]
  command = "git submodule init && git submodule update && hugo -b gabe.kitchen --gc --minify"