# [build]
#   publish = "public"
#   functions = "functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "git submodule update --init --recursive --remote && hugo -b gabe.kitchen --gc --minify"